### PR TITLE
Update pdfbox-box binding to version 2.0.0.0

### PR DESCRIPTION
**Pull request by 4brunu**
This PR updates the pdfbox-box binding to version 2.0.0.0.
I have tested it in the sample project and it's working.

### CODE REVIEW

**Comment by gsgou** [comment]
Thanks once again @4brunu :) I missed this PR in the hospital :D

**Comment by 4brunu** [comment]
Sorry to ear that, are you ok now? :/

**Comment by gsgou** [comment]
Thanks @4brunu. I had an ear infection and went to the emergency before my flight where i got infected with Covid.
A chain of circumstances. Ended up having severe symptoms but finally i am now in the end phase of pneumonia :)
All good. Wish you health mate and a wonderful summertime in beautiful Portugal.

**Comment by 4brunu** [comment]
Thank God you are better now 🙂 
Have a good recovery.
Thanks also for merging this PR.
PDFBox-Android has a new release today, so I may create shortly another PR to update to 2.0.1.0 🙂

**Comment by gsgou** [comment]
Noticed the underlying PdfBox got updated. I added you as collaborator. You can directly commit to the project now. Thanks for taking care this one :)

**Comment by 4brunu** [comment]
Thanks 👍 
So how should I proceed?
Instead of creating PRs, should commit directly to the repo?
And then ping you to publish the new version in the nuget?

**Comment by gsgou** [comment]
Sounds great as described above. I ll see if there is a way to invite you also in the nuget project else simply ping me :)

**Comment by 4brunu** [comment]
Thanks 👍 
Should I wait for version 2.0.0.0 to be published and then merge https://github.com/gsgou/Xamarin.Android.PdfBox/pull/5 so that both 2.0.0.0 and 2.0.1.0 can be published?
Or should we merge https://github.com/gsgou/Xamarin.Android.PdfBox/pull/5 now, and only publish 2.0.1.0?

**Comment by gsgou** [comment]
I ll publish both versions as nugets just for the shake of completion.

**Comment by 4brunu** [comment]
Looks good to me, thanks for helping 👍

**Comment by gsgou** [comment]
@4brunu if you have a nuget username to share i can also add you there as package owner ;)

**Comment by 4brunu** [comment]
it's also 4brunu :)

**Comment by gsgou** [comment]
I have build the nugets and testing them before release.
I am adding you as owner so next time you can release the nuget as well.
I ll add a script later with the commandline to run it from the project path with a version name.

**Comment by 4brunu** [comment]
Thanks 👍

**Comment by gsgou** [comment]
Packages are published. Added you in nuget. Put a lot of trust on you :)
Note: All package owners have full control over their packages, including the ability to remove other users as owners.

**Comment by 4brunu** [comment]
Thanks, but no need for such permissions, being able to upload new version is enough 🙂

**Comment by gsgou** [comment]
There is no other permission then ownership. I have no worries about ya. Happy you can update the nuget too now :)

**Comment by 4brunu** [comment]
Thanks 👍 
Maybe on some next update I can try to publish it to nuget with your help to make sure I don't make any mistake 🙂

**Comment by gsgou** [comment]
Added a bash build script. You can run it from proj path as `./build.sh` after setting VersionPrefix in csproj or as `./build.sh 2.0.1.0` with some version major.minor.patch[.build] provided. Build number is omitted if not different then zero.

**Comment by 4brunu** [comment]
Thanks 👍

**Comment by gsgou** [comment]
If you ll find time you can maybe migrate the sample to AndroidX.

**Comment by 4brunu** [comment]
Can you please review the following PR to ensure that I didn't something wrong?
https://github.com/gsgou/Xamarin.Android.PdfBox/pull/6
Thanks 👍

**Pull request merged**
