### PR TITLE
Update binding to 2.0.4.0

### PR DESCRIPTION
**Pull request by 4brunu**
Hey @gsgou,

I have updated the binding to 2.0.4.0 that also fixes https://github.com/gsgou/Xamarin.Android.PdfBox/issues/8

I have tested it and it doesn't crash anymore.

### CODE REVIEW

**Review by gsgou — APPROVED** [review]
Thank you buddy

**Comment by 4brunu** [comment]
I try to update the package on nuget to see if everything goes okay 🙂

**Comment by 4brunu** [comment]
Done, it's published 👍

**Comment by gsgou** [comment]
Perfect, have a nice start in the week @4brunu !

**Comment by 4brunu** [comment]
Thank you, the same for you 🙂

**Pull request merged**
